project:
  title: "Foundational Community Building"
  type: book
  output-dir: docs

book:
  author: "Malvika Sharan"
  date: "10/12/2021"
  page-navigation: true
  downloads: epub
  cover-image: fcb-cover.jpg
  illustrator: The Turing Way and Scriberia
  chapters:
    - index.md
    - community-narrative.qmd
    - cop-basic.qmd
    - community-engagement.qmd
    - community-charter.qmd
    - open-research-implementation.qmd
    - logistics.qmd
    - References.qmd

toc: true
number-sections: false
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport
  epub:
    cover-image:

editor:
  render-on-save: true