project:
  title: "Foundational Community Building"
  type: book
  output-dir: docs

book:
  author: "Malvika Sharan"
  page-navigation: true
  search: true
  repo-url: https://github.com/malvikasharan/community-building-foundational-training
  date: "10/12/2021"
  downloads: epub
  cover-image: fcb-cover.jpg
  illustrator: The Turing Way and Scriberia
  chapters:
    - index.md
    - community-narrative.md
    - cop-basic.md
    - community-engagement.md
    - community-charter.md
    - open-research-implementation.md
    - logistics.md
    # - references.md

toc: true
number-sections: false
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport
  epub:
    cover-image:

editor:
  render-on-save: true