# Session 3: 🗺 Community Engagement

> *Just because you can draw a detailed map, doesn’t mean you are accurately representing the territory!* - Yuval Noah Harari

## Key lessons
- information mapping for your community
- Building a mountain/matrix of engagement
- Understanding and mapping incentives and value-exchange

## Roll call

**Name / reflect on what you as a community builder/facilitator/participant bring into your community space and what do you receive+give back?** (kindness, empathy, professional expertise, resources, technical knowledge, mentorship etc.) / **Does this balance seem right?**

- Participants response ...
-
-


## 🖥 Part 3: Community participation and Value-exchange

[[Link to the Google slides](https://docs.google.com/presentation/d/11LH1edg_0srL2ibTl2mVnsICIydtT0i2WC93TsjacsM/edit#slide=id.g13faa93073d_0_1507)]

**In this session, we will build a clear understanding of :**

- what different resources and processes in our community exist
- what do different kinds of community participation and engagement look like
- what values do we create for our community members to participate in our community and engage with our work
- what processes work that can be used to iterate and improve all forms of participation and build a fair value exchange (support and acknowledgement) system

_ **Mapping community information, community process, the mountain of engagement and value exchange** _

- Discover how people interact with your community, organisation, or project and its culture.
- Discover how people identify and move between different types of interactions.
- Develop pathways for people to move from first contact to sustained engagement to leadership
- Embed value-exchange and fair recognition process in the project

**Notes**

- Participants response ...
-
-

📝 **Assignment:**

[[MAKE A COPY] 3 - community participation and engagement ](https://docs.google.com/document/d/1JtsNwZUHtSfKQKeyR36e97tgN8BR-MQEMx2MHNtBsYI/edit#) **← [Make a Copy]**

**TODO:** Bring one or multiple of these resources to share with others

- Your favourite community document - from your or another project - these documents could be an annual report, a community health report (how is your community doing, what are the indicators)
- A community policy from your work (contributing guideline, code of conduct etc.) 
- Strategy or communication document.

**Reading recommendation**

- Personas and Pathways: [https://the-turing-way.netlify.app/project-design/persona.html](https://the-turing-way.netlify.app/project-design/persona.html)
- Jones, C. M. (2022). How to Reward Your Community Members And Keep Them Engaged. CMX. [https://cmxhub.com/how-to-reward-your-community-members](https://cmxhub.com/how-to-reward-your-community-members)
- Creating Pathways: [Creating Pathways That Invest in New Maintainers](https://medium.com/@abbycabs/creating-pathways-that-invest-in-new-maintainers-8ffb52e09681)
- Map is not the territory: [https://conceptually.org/concepts/the-map-is-not-the-territory](https://conceptually.org/concepts/the-map-is-not-the-territory)
- How do we manage conflict and difficult situations
  - Positive Deviance. (2018, July 12): [https://involve.org.uk/resources/methods/positive-deviance](https://involve.org.uk/resources/methods/positive-deviance)
  - Code of Conduct and Restorative practice: [https://github.com/alan-turing-institute/open-community-building/blob/main/CODE\_OF\_CONDUCT.md#6-restorative-practice-statement-and-principles](https://github.com/alan-turing-institute/open-community-building/blob/main/CODE_OF_CONDUCT.md#6-restorative-practice-statement-and-principles)
  - What is Conflict Management? | peopleHum: [https://www.peoplehum.com/glossary/conflict-management](https://www.peoplehum.com/glossary/conflict-management)
  - Restorative Practices – Conflict Resolution Education Connection: [https://creducation.net/conflict\_resolution\_education\_practice\_areas/restorative\_practices](https://creducation.net/conflict_resolution_education_practice_areas/restorative_practices)
  - The Positive Value of Conflict: The Power of Resolution: [https://www.psychologytoday.com/gb/blog/inside-out-outside-in/202103/the-positive-value-conflict-the-power-resolution](https://www.psychologytoday.com/gb/blog/inside-out-outside-in/202103/the-positive-value-conflict-the-power-resolution)

## 🏡 Key takeaways

**In this next session we discussed the Mountain/Matrix of engagement to understand what different levels of engagement looks like and how we facilitate that.**

We explored questions and frameworks to understand these aspects:
- How do we move our community contributors/stakeholders from one level to another? When to recognise someone can move from one band to another?
- Mountain of Engagement should be a living document, reflecting on what your community experiences are and where you should modify them.

### Q&A and suggestions after the call - response will be shared through notes

- Participants response ...
-
-

### Feedback from this session

_What worked? What didn't work? What would you change? What surprised you?_
- Participants response ...