# Session 4:  📜 Creating and Communicating Community Charter

> *Values are the rules by which we live – the filters through which we evaluate possible actions, the base upon which we make decisions in support of the achievement of our collective and individual vision and purpose.* –_ Michael Cavanagh

### Key lessons

- Framing your community vision
- Communicating your community mission
- Defining roadmaps and milestones
- Establishing ways of working

### Roll call

✏️ _ **Silent reflection 5 mins, exchange thoughts with the group** _

- **Identify your core values (pick 3)** ([LIST OF PERSONAL CORE VALUES](https://thehappinessplanner.co.uk/pages/list-of-core-values))
- Choose one and define how you see it, Offer examples of your chosen value in action - share with others

_Name / Three Values (based on where you currently are - this may change in the future)_

- Malvika / Accountability, **Transparency** , Kindness,
- Participants response ...
-
-

**Personal Reflections**

- _How do your values align with the work you do?_
- _How would you help a contributor align their values, vision and goal?_
- _What will this discussion between you and them look like?_

[[Link to the Google slides]](https://docs.google.com/presentation/d/1JZt3HQMKg_6Eu3ctHH3PUv-9LgdTwFpyYhkrOwf5AUs/edit?usp=sharing)

"_A goal is not always meant to be reached, it often serves simply as something to aim at." ― Bruce Lee_

## Vision: Articulating your big ideas (for the future)

### Prompts for vision

- What you are doing - Why you are doing this - the impact or change your project will bring - Who are users and contributors

## Mission:** Where you are right now, what your objectives are, what is next.

### Prompts for Mission

- What the objectives are - What does your project offers and what makes it unique - What the next steps are (Process for community engagement and project development)

## Roadmap: an overview of the project's goals and outcomes presented on a timeline.

- Roadmap is supplemented with details such as scope, resources, ways of working, risks
- Roadmap does not provide task-level details. (For task-level details, see project charter).
- Information gathered so far can be put together in a project charter, or maintained through separate documents. You can consider adding more details. (Prompts in the assignment)

### Reflection for the future

What is the definition of success for us in 6 months/12 months/2 years (based on where you are)?

**Shared notes/thoughts/insights**

- A vision statement can be hard to draft when other stakeholders are not in the same room
- Writing something short and succinct can take more time than multiple sentences - it can be iteratively improved, but you need to start somewhere
- Participants response ...
- 
-

## 🏡 **Next steps: In your own time after the workshop!**

_ **Integrating values and intentional efforts for inclusion and diversity in your project.** _

**Before doing the assignment:**

Identify your community's values and represent them in all processes (policies, guidelines, onboarding, decision-making, communication etc.)

## 📝 **Assignment 4 + Discussions:** [4 - Community Vision, Mission, Roadmap, Charter](https://docs.google.com/document/d/1c5NDGUnVc-L5DPop3UvpgOw3XuZHrY5B1wQ9mBWWoXg/edit?usp=sharing)**← [Make a Copy]**

**Reading recommendation:**

- [6-AuthenticPrinciplesCommEng.pdf](https://drive.google.com/file/d/1dzTWPNXwPCAMZJBiEBf0a4c_y9F3Bvk1/view?usp=sharing) _(reference:_ [_Principles of Authentic Community Engagement_](https://www.health.state.mn.us/communities/practice/resources/phqitoolbox/authenticprinciples.html) _- Minnesota Dept. of Health. (2014, September 28).)_

## 🏡 Key takeaways

**In this session, we learned how to build a community charter - emphasising the importance of building clarity in your work through writing.**


### Q&A and suggestions after the call - response will be shared through notes

- Participants response ...
-
-

### Feedback from this session

_What worked? What didn't work? What would you change? What surprised you?_
- Participants response ...