# Logistics for Facilitators and Attendees

This workshop session brings new community managers or members in community coordination roles together in a cohort format to introduce foundational skills for community management, while encouraging them to share skills, experiences and ideas for collaboration with each other.
    
Here is a recommendation for participants to help with keeping this workshop series as interactive as possible, while ensuring that everyone the chance to contribute to the discussion:

- If you generally take less space, please use this workshop to take more space.
- If you generally take space, try to give space to others. 
- We will have many quiet reflections during the training.
- Silence can be awkward but that is not a sign that others who are often not the first one to speak have nothing to add.

## Participation guidelines for the workshops

* The workshop facilitator will introduce topics through short presentation, followed by either a quiet assignment (by yourself) or breakout room (group discussion), followed by full group reflection and sharing insights.
* We will use a shared web-based clock to ensure keeping discussions on time using Cuckoo Clock [cuckoo.team](https://cuckoo.team) <-- update for you
* A shared document will be set up for each session with information guiding the format, space for documenting notes collaboratively, and sharing resources (links, thoughts, examples)
  * You can leave and come back to the workshop as it suits
* We encourage sharing feedback to make sure that this and future sessions are beneficial for all of us.
  * If you experience something that makes you uncomfortable (topic, conversation or format of any certain session), please let me (Malvika) know privately (msharan@turing.ac.uk) so that I can act immediately.
* Each call will be paired with an assignment to help you reflect on the practices in the context of your project. We will allocate 10 minutes in the following call to share insights from our assignments with others. Although I can not make it mandatory for you to complete this assignment, it will be more effective if you take some to complete them. If you feel comfortable, you can share the links to your assignment in the shared document.

## Format

- Each lesson has been designed for 1 hour.
- Additional 20-30 minutes of the workshop sessions should be reserved for open discussion and sharing insights from our assignments with others.
- Lessons are provided in a format that can be copied directly on a shared document for teaching purpose. 
- Each lesson has been paired with practical assignments to help learners reflect on the practices in the context of their projects.
- Before each lesson, please provide details such as date, time and joining link for the session, and create a space for feedback (pluses and delta) and reflections (such as what was the main takeaway for participants personally, what was not clear) at the end of each session.

### Joining the call

- Please inform participants if the presentation part of this call can be recorded for people who are unable to attend this session.
- The discussion part should not be recorded to allow honest and open discussion.

### Roll call

For each session, I recommend using roll call with icebreaker question prompting reflections related to the content.
Below are suggestion for each session:

- Session 1 icebreaker question: *What is one characteristic about a community you most admire? Have you been able to replicate that for your project? If yes, how? If not, why not?*
- Session 2 icebreaker question: *Reflections from learning about your community and building a narrative - what was most surprising?*
- Session 3 icebreaker question: *Reflect on what you as a community builder/facilitator/participant bring into your community space and what do you receive+give back?** (kindness, empathy, professional expertise, resources, technical knowledge, mentorship etc.) / **Does this balance seem right?*
- Session 4 icebreaker question: From the [LIST OF PERSONAL CORE VALUES](https://thehappinessplanner.co.uk/pages/list-of-core-values), select and share three values based on your currently work (this may change in the future)

### Concluding the Session

At the end of the shared document for each session - you can ask for two post session inputs:

- Questions and suggestions (response can be shared asynchonously through notes)
- Feedback from the sessions: _What worked? What didn't work? What would you change? What surprised you?

## Below are some potential topics for additional modules:

- **Open Science/research framework**: applying open, equitable and participatory approaches for building communities
- **Facilitating community events**: Good practices for online vs in person facilitation of community events
- **Impact assessment and reporting**: What are some good practices and frameworks for impact assessment in the community, and how do we report them
- **Conflict management** and handling a difficult situation

### Anything else?

Have suggestions for more topics? Share them with me by emailing [msharan@turing.ac.uk](mailto:msharan@turing.ac.uk).

***Happy community building!***