# Session 5: 🔓 Open Research Implementation

**DRAFT PRE-ALPHA VERSION FOR ONLINE WEBPAGE**

> ** – 

## Key lessons

* 

[Mutual Learning Exercise: Open Science – Altmetrics and Rewards. Thematic Report No 4](https://ec.europa.eu/research-and-innovation/sites/default/files/rio/report/MLE%2520OS_4th%2520thematic%2520report.pdf). 
Prepared by the independent expert: Sabina Leonelli (2018). Implementing Open Science: Strategies, Experiences and Models. 

| Key principles | Overview |
|:---------------|:---------|
| Respect for Diversity | Research works best when involving different actors with different qualities, and the incentive system must recognise and reward such diversity. Furthermore, buy in from researchers themselves is necessary for Open Science policies to work. |
| Collaboration	| Open Science can only be realised through collaboration among different institutions, research fields, stakeholders (including funders, universities, government departments, libraries and learned societies) and countries. |
| Accountability | Stakeholders in Open Science need to explicitly and clearly take responsibility for different aspects involved in its implementation, and be accountable for the degree and mechanisms through which these aspects are achieved. |
| Transparency | Make it possible for any stakeholder (including the general public) to engage in the ongoing discussions and understand the rationale behind specific actions and guideline. |
| Social responsibility and engagement | Ethical and social concerns, as well as consultation and mechanisms for social participation, need to be incorporated into the implementation of Open Science at every stage. |
| Fairness | "Make sure that actions resulted by your work are targeted at the diverse needs and situations in different countries and research fields – and that minority/priviliged groups do not benefit disproportionately." |
| Impact | Open Science is about improving the quality, accountability and social contribution of research while striving to minimise bureaucratic and administrative burdens on researchers and research institutions. |